name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testes_unitarios:
    name: "Integração"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalação de dependências
        run: pip install -r requirements.txt
      - name: Testes unitários
        run: pytest
  analise_estatica:
    name: "Bandit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalando bandit
        run: pip install bandit
      - name: Análise estática
        run: bandit -r .
  